SET SERVEROUTPUT ON;
DECLARE

SALARIO NUMBER(10,2):=1412.00;
REAJUSTE SALARIO%TYPE;

BEGIN
REAJUSTE := SALARIO*1.25;

DBMS_OUTPUT.PUT_LINE('VALOR DO SALARIO É: '||SALARIO);
DBMS_OUTPUT.PUT_LINE('VALOR DO SALARIO REAJUSTADO É: '||REAJUSTE);

END;