SET SERVEROUTPUT ON;
DECLARE

V1 NUMBER (10,2) :=125.60;
NOME VARCHAR2(10) := 'Allesson';
V2 V1%TYPE := &DIGITE_VALOR_DA_V3;

BEGIN

DBMS_OUTPUT.PUT_LINE('VALOR DA V1 É:'||V1);
DBMS_OUTPUT.PUT_LINE('VALOR DA VARIANTE NOME É:'||NOME);
DBMS_OUTPUT.PUT_LINE('VALOR DA V2 É:'||V2);
DBMS_OUTPUT.PUT_LINE('VALOR DA V3 É:'||V3);

END;

